### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by z0mbooy** [Znunu/EzMudae#1]
Do you happen to claim desired waifus?

**Comment by Znunu** [comment]
I don't completely understand your question, but I'll try my best to answer anyway. This isn't a bot in itself, it's just a module/library. That being said, I wouldn't mind adding a function to the Waifu class, that claims the waifu. It's actually already in the TODO.md file.   Not that it isn't already trivial to claim a desired waifu, using the Waifu class.

**Comment by z0mbooy** [comment]
Sorry if you did not explain me well, I am somewhat new to this, but I am interested to know if this module can claim waifus that are in a desired list, and anyway how I configure it to put it. Thank you very much for answering

**Comment by Znunu** [comment]
I added a code snippet in README.md that shows you how to claim. Gonna put it here too:
```python
mudae_wrap #A Mudae object

async def on_message(message)
      
      # My wishes
      wishlist = ("saber", "suzuha", "hatsune miku")
      
      # Check if the waifu is in a wishlist
      waifu = mudae_wrap.from_wish(message, wishlist)
      
      # If it is, claim it
      if (waifu):
            await waifu.add_reaction("❤️")
```
Regarding setting it up. I'm assuming you're familiar with discord.py and python. Just add the module to your project and then import it.

**Comment by Znunu** [comment]
No reply after almost a month
