### ISSUE TITLE
Documentation Website is down

### ISSUE THREAD

**Issue by Vandennn** [Znunu/EzMudae#6]
I went to check the documentation out but the website it's on was down so I was wondering if there was a copy of it somewhere.

**Comment by Znunu** [comment]
Sorry about that
Here's documentation for the Mudae class http://orz.cx/pub/misc/mudae.html
and for the waifu class http://orz.cx/pub/misc/waifu.html

The docs are really broken atm. The docs only consist of these two pages, which link to each other. However, those links will just send you to a 404 page. You should be alright though, as I've linked them both correctly here

**Comment by Znunu** [comment]
Fixed docs. New urls are in readme.md
