### ISSUE TITLE
until_roll giving values way beyond roll_mod

### ISSUE THREAD

**Issue by JUSTadICE-CHaN** [Znunu/EzMudae#7]
i obtained timing globaly in my program using arbitrary values:

```timing = get_timing(60, 180, 0, 0)``` 

Then a mudae_wrapped object was created on async on_message

mudae_wrap = Mudae(self, timing)

but then when going to print the time until_roll rather than seeing values at 60 or below, I receive values that are around 600+

```print(f'{mudae_wrap.until_roll()} until next roll')```

**Comment by Znunu** [comment]
I've tried to fix it, however I didn't really test the fix... "^_^. let me know if it works now. also, you can join my discord server: https://discord.gg/kw6PCBaW5y
